### ISSUE TITLE
Lock width in dark themes

### ISSUE THREAD

**Issue by FabricioManfrin** [grosenberg/IndentGuide#10]
I have indent guide and darkest dark theme with devstyle running in eclipse:

Version: 2021-06 (4.20.0)
Build id: 20210612-2011

The width preference does not appear to save. Each time I restart Eclipse width resets to 4 which is way too wide for my liking. All other preferences - alpha, style, shift, color, and the drawing options, appear to correctly save and reload on startup.

I tried this workaround - https://github.com/grosenberg/IndentGuide/issues/7 - but it did not seam to work. 
When I uninstalled, the darkest dark indent guide work perfectly. I know that I'm asking a bit of a stratch here but on wanting to make it work with two plugins, but I'm desperate trying to find a solution.

What I know is that when eclipse re-loads, the file color-definitions-fix.css:

**<workspace>\.metadata\.plugins\com.genuitec.eclipse.ui.common.platform\color-definitions-fix.css**

It re-writes these lines:

    IEclipsePreferences#net-certiv-tools-indentguide {
        preferences:
            'indentguide.line_color=185,192,198'
            'indentguide.line_width=4'
    }

I understand if what I'm asking is too much, but i really tried fixing this on my on but i don't have the knowledge to do so, I'm asking for help.

**Comment by FabricioManfrin** [comment]
With a little more digging, I discovered that is not a conflict. Indent Guide by default in dark themes it reset the width in lines attributes to 4 and in light themes it by default 1. What I'm trying to find now is a way to disable this lock functionality to have option of width of 1 in dark themes.

**Comment by grosenberg** [comment]
This is purely an issue with Genuitec not correctly reading the plugin preferences. No fix to IndentGuide will fix this.

**Comment by FabricioManfrin** [comment]
I uninstalled all plugins, just leaving Indent Guide, when use the default dark theme and set up the width to 1, each time I restart Eclipse width resets to 4. But the default width for light themes is 1. What I think is happening is that is there is a default function that it's resetting the settings for the theme every time it starts Eclipse. I don't know to be honest, just reporting to you.
