### ISSUE TITLE
Setting not been kept in dark theme

### ISSUE THREAD

**Issue by FabricioManfrin** [grosenberg/IndentGuide#11]
Eclipse:
Version: 2021-06 (4.20.0)
Build id: 20210612-2011

I uninstalled all plugins, just leaving Indent Guide, when use the default dark theme and set up the width to 1, each time I restart Eclipse width resets to 4. But the default width for light themes is 1, the preferences in width saves when you keep a light themes, but not in dark in the dark theme.

Setting that are lost in restart:
-Width

What I think is happening is that is there is a default function that it's resetting the settings for the theme every time it starts Eclipse. I don't know to be honest, just reporting to you.

**Comment by grosenberg** [comment]
This is purely an issue with Genuitec. No fix to IndentGuide will fix this.

You have previously reported this. Reporting it again here wont fix their problem
