### ISSUE TITLE
Indent guide width setting isnt saved

### ISSUE THREAD

**Issue by avners** [grosenberg/IndentGuide#12]
When trying to save a changed value of the indent guide width, the change does not survive reboot
in order to bypass this i added the row indentguide.line_width=1 to the file: \.metadata\.plugins\org.eclipse.core.runtime\net.certiv.tools.indentguide.prefs

**Comment by grosenberg** [comment]
Settings are known to be saved properly in standard Eclipse setups. 

There have been problems when using third-party plugins that attempt to manage the overall platform configuration/styling -- they often provide exceptions for well-known plugins, but IndentGuide is not sufficiently well-known. 

See https://github.com/grosenberg/IndentGuide/issues/7

To diagnose the problem, disable all third-party plugins other than IndentGuide, and verify correct behavior without your 'fix'. Then begin re-enabling your third-party plugins.

Please let me know if you are able to identify the conflicting plugin.

**Comment by fpierrat** [comment]
Hi,

First of all, thanks for this plugin.

I have the same issue as Avners (Indent Guide 1.6.3).
The only other plugin installed was SQL Editor. 
Following your suggestion, I just:
- uninstalled it, 
- restarted Eclipse,
- set the pref General/Editors/Text editors/Indent Guide/Width to 1 pixel,
- restarted Eclipse again
=> the pref hasn't been saved, width is still 4 pix.

Eclipse Help/About infos if useful: 
    Eclipse IDE for PHP Developers (includes incubating components)
    Version: 2021-12 (4.22.0)
    Build id: 20211202-1639

Eclipse Help/About "installation details":
![image](https://user-images.githubusercontent.com/16537778/162695707-6baec53a-cba2-433f-a997-f2c087cb1209.png)


[EDIT] Manually modifying the prefs file as described by Avners worked, thanks @avners

**Comment by grosenberg** [comment]
See #7

Did you check Oomph? Not familiar with the PHP Remote project sync plugin.

In every case that where the non-save problem has been replicated, the source of the problem has been another/third-party plugin that is resetting options on startup or dynamically blocking options from being persisted across sessions.
