### ISSUE TITLE
Guide continue on empty line after multiline code

### ISSUE THREAD

**Issue by Benik3** [grosenberg/IndentGuide#14]
Hello.
First thanks for this plugin! :)
I have one improvement - if you have multi line code, it's also marked by IndentGuide, but the line continue even on empty line after this code. Is possible to remove the guide from the empty line?
I know there is option Draw guide on blank lines, but it makes holes in all guides.
Also for some reason it makes two lines for one command.

![image](https://user-images.githubusercontent.com/4532647/171117400-73e9e4aa-8624-4017-b97e-a68d5420d0ba.png)

**Comment by grosenberg** [comment]
Upon review, don't think this is a desirable addition.
