### ISSUE TITLE
[Question] Could you contribute this great feature into Eclipse ?

### ISSUE THREAD

**Issue by gayanper** [grosenberg/IndentGuide#16]
Hi,

Are you open for contributing this great feature into Eclipse Platform Text component ?

**Comment by grosenberg** [comment]
Do you represent the Eclipse Foundation or one of the Eclipse groups?

**Comment by gayanper** [comment]
Sorry for late reply, I'm committer in Eclipse JDT and if you would like to contribute I can create a issue in Eclipse Platform Text project where this functionality can be moved to. WDYT ?

**Comment by grosenberg** [comment]
Certainly open to exploring the possibility.

**Comment by gayanper** [comment]
Ok i will open a issue in eclipse-platform project and tag you. Then we can proceed from there how to contribute and licensing with the project members.

**Comment by vogella** [comment]
FYI, I'm one of the project leads of Eclipse. 

Moving this feature to Eclipse standard would be great, I miss this very much in default Eclipse. @grosenberg could you add a PR for this to the eclipse.platform.text repo? I think we should have also a preferece to enable/ disable it for text editors.

Thanks @gayanper and @grosenberg for considering to contribute this, this will make my life much better with using Eclipse.

**Comment by grosenberg** [comment]
While incorporating support for indent guides in platform.text is doable, the amount of work required to prepare a PR to correctly incorporate a new painter is unfortunately beyond what I can invest at this time.
