### ISSUE TITLE
Support of Multi-page editor

### ISSUE THREAD

**Issue by marmyshev** [grosenberg/IndentGuide#17]
Very often happens that text editor might be a page of some multi-paged editor.

So, somewhere here https://github.com/grosenberg/IndentGuide/blob/master/net.certiv.tools.indentguide.plugin/src/net/certiv/tools/indentguide/Starter.java#L119 or L-105 - should check that current editor is `org.eclipse.ui.part.MultiPageEditorPart` or instance of `org.eclipse.jface.dialogs.IPageChangeProvider` then get `org.eclipse.jface.dialogs.IPageChangeProvider.getSelectedPage()` to check if it is text editor.
Also add listener of `org.eclipse.jface.dialogs.IPageChangedListener` to catch activation of other text editor on other page.

**Comment by marmyshev** [comment]
I can contribute this feature, if you want.

**Comment by grosenberg** [comment]
No problem identified.

**Comment by marmyshev** [comment]
This is weird :) There is the problem. 

For example: we have some editor which is MultiPageEditorPart. But the needed text/code editor is on some 2-nd or other than first page. Also in this multi-page editor we could have several text/code editors on different pages.

 In this case plugin "painter" will not be installed to the target text editor. And questions is: which one of many text editors we should install the painter? This leads us to use IPageChangeProvider to catch page changing.

**Comment by grosenberg** [comment]
The listener for the painter is installed for every `IEditorPart` opened -- the parent interface of all editors including the `MultiPageEditorPart`.  Are you actually seeing a problem and, if so, what is it?

**Comment by grosenberg** [comment]
There is a pre-releease v1.8.0 available under the [Releases](https://github.com/grosenberg/IndentGuide/releases) link. 

TBC: download the zip to a local folder and use the 'Archive' option on the Install New Software -> Add Repository dialog.

**Comment by grosenberg** [comment]
Fixed with the 2.0 release.
