### ISSUE TITLE
Problem with DPI Scaling 

### ISSUE THREAD

**Issue by christiankarsch** [grosenberg/IndentGuide#18]
On my UHD Monitor with DPI Scaling 175% the Intent Lines are on wrong positions
Looks like all lines are shifted by a factor of 2

![image](https://user-images.githubusercontent.com/3510491/207669777-37da5a89-f75b-4dc5-916d-a6ded50ec6b0.png)
![image](https://user-images.githubusercontent.com/3510491/207666986-47a65686-d867-43f9-b174-1aac6e762fec.png)
![image](https://user-images.githubusercontent.com/3510491/207666481-b926382b-3932-42f1-8a09-636506327ac1.png)

When i change temporrey to 100% the lines are in the right position.
![image](https://user-images.githubusercontent.com/3510491/207669263-b7c5e626-a113-49c2-82b6-133e370d02b7.png)
(Windows 10)

**Comment by grosenberg** [comment]
Need your Eclipse and platform JRE versions

**Comment by grosenberg** [comment]
Does not appear to be an issue that can be addressed by plugin code - the Java runtime is supposed to handle all DPI scaling issues internally.

**Comment by grosenberg** [comment]
Subtle bug. Hopefully will be fixed in the next release.

**Comment by grosenberg** [comment]
There is a pre-releease v1.8.0 available under the [Releases](https://github.com/grosenberg/IndentGuide/releases) link. 

TBC: download the zip to a local folder and use the 'Archive' option on the Install New Software -> Add Repository dialog.

**Comment by grosenberg** [comment]
Fixed with the 2.0 release.
