### ISSUE TITLE
Offline Install

### ISSUE THREAD

**Issue by Nmidia** [grosenberg/IndentGuide#19]
Hi,  Could you provide an archive for installing this in an offline environment please.  We have no internal internet connectivity so have to point to an archive.  Thanks

**Comment by grosenberg** [comment]
[net.certiv.tools.indentguide.site-1.7.1-SNAPSHOT.zip](https://github.com/grosenberg/IndentGuide/files/10538763/net.certiv.tools.indentguide.site-1.7.1-SNAPSHOT.zip)

This is the current development snapshot.
