### ISSUE TITLE
Eclipse 2023-03 new feature line spacing support

### ISSUE THREAD

**Issue by cypher256** [grosenberg/IndentGuide#22]
Eclipse 2023-03 New feature Line Spacing
![image](https://user-images.githubusercontent.com/1156871/224466071-9bbf2dd5-280e-49cd-a414-17d5448d09b9.png)

Line Spacing 0% (default)
![image](https://user-images.githubusercontent.com/1156871/224466330-3b745814-4621-44a9-a72e-302c9fa034a8.png)

Line Spacing 80%
![image](https://user-images.githubusercontent.com/1156871/224466102-6cf56ba5-9450-4d03-a471-933e10b3e130.png)

Is it possible to avoid vertical spacing of indent lines?
eclipse-java-2023-03-R-macosx-cocoa-x86_64.dmg (Intel Mac)
eclipse-java-2023-03-R-win32-x86_64.zip (Windows 10 Pro)

**Comment by grosenberg** [comment]
Do not  have that version yet.

Do expect that it can be fixed, provided "they" have added the new line spacing info to the `PaintEvent`.

**Comment by grosenberg** [comment]
A pre-release is [available to test](https://github.com/grosenberg/IndentGuide/releases)

**Comment by cypher256** [comment]
Excellent!
It worked fine with v2.2.0-SNAPSHOT even with the line spacing set.
