### ISSUE TITLE
Indentation shifts when nesting is deep

### ISSUE THREAD

**Issue by cypher256** [grosenberg/IndentGuide#23]
The deeper the nest, the more the indentation shifts step by step.
v2.2.0-SNAPSHOT (default settings)

Intel macOS 12.6.3 (21G419)
eclipse-java-2023-03-R-macosx-cocoa-x86_64.dmg (default settings)
![mac](https://user-images.githubusercontent.com/1156871/226079595-62474ee3-c556-4dae-8210-d21df4c05ac8.png)

Windows 11 Pro 22H2
eclipse-java-2023-03-R-win32-x86_64.zip (default settings)
![win](https://user-images.githubusercontent.com/1156871/226079603-d5e257d3-7f2c-4d16-9b2c-c5d02d80c299.png)

May be related to #22, overlapping vertical lines on Windows?

**Comment by grosenberg** [comment]
What font are you using?

**Comment by cypher256** [comment]
All settings are default, freshly installed and clean.
However, the OS is a Japanese environment.

### Mac Menlo 12
[_mac_config.txt](https://github.com/grosenberg/IndentGuide/files/11010104/_mac_config.txt)
![image](https://user-images.githubusercontent.com/1156871/226151144-b8f30db4-7584-4d36-bc8e-bc1d8ec338a6.png)

### Win Courier New 10
[_win_config.txt](https://github.com/grosenberg/IndentGuide/files/11010105/_win_config.txt)
![image](https://user-images.githubusercontent.com/1156871/226151094-2b0ed293-5b70-4add-9463-09d358b327e6.png)

**Comment by grosenberg** [comment]
Certain fonts -- most notably Source Code Pro -- report the wrong metrics.  Courier New and Menlo report correctly (consistent with most other fonts).

Maybe try updating your fonts or switching to another, such as Fira Code.

Courier New
![CourierNew](https://user-images.githubusercontent.com/1757970/226204935-8be8fe95-7a42-430d-be0f-b4730c85eded.jpg)

Menlo
![Menlo](https://user-images.githubusercontent.com/1757970/226204959-9e6cca59-2cef-4e81-a2f6-b629d5f09b03.jpg)

Source Code Pro
![SourceCodePro](https://user-images.githubusercontent.com/1757970/226204978-c88f9925-8c68-4373-a0ba-07b3785c383d.jpg)

**Comment by cypher256** [comment]
The font size seems to be affected in my environment.
Windows 10 Pro, Eclipse 2023-03 (4.27.0), Eclipse Runtime Java Adoptium 17.0.6+10
OS Display Scaling 100%, No autoScale settings in eclipse.ini
IndentGuide v2.2.0-SNAPSHOT (default settings)

|Font Size =|8|9|10|11|12|14|
| --- | --- | --- | --- | --- | --- | --- |
|Courier New|❌|✅|❌|✅|❌|✅|
|Source Code Pro|❌|✅|❌|❌|❌|✅|

Courier New 9
![image](https://user-images.githubusercontent.com/1156871/226271669-8b3db965-138d-4ae7-81a3-a966e2a55144.png)

Courier New 10
![image](https://user-images.githubusercontent.com/1156871/226271869-3970a65c-2add-42b1-a740-6e3afba361bb.png)

Source Code Pro 9
![image](https://user-images.githubusercontent.com/1156871/226272020-febda7b3-f782-45be-8316-62a5e00447c8.png)

Source Code Pro 10
![image](https://user-images.githubusercontent.com/1156871/226272137-450731a1-b1e7-4b06-ac8d-e2fca5813651.png)

**Comment by grosenberg** [comment]
The font/font size is all handled by the graphics context of the Java VM. If the width of a space is not reported correctly, the draw x/y will not be correct.

For most fonts, even proportional fonts, the reported font metrics are correct.  Why, for some, it is not I do not know.  

Your test data suggests there is some (bad) OS/VM font size interpolation going on, but that is just a WAG.

Nothing I can do at this end.

**Comment by grosenberg** [comment]
Fixed in release v 2.2.2
