### ISSUE TITLE
Guides shifts inequvalent to tab size in source

### ISSUE THREAD

**Issue by molostoff** [grosenberg/IndentGuide#26]
![image](https://user-images.githubusercontent.com/857920/227328908-ca55602e-0754-401b-acec-b6e59085e23f.png)

Font: Liberation Mono size: 7
Tab size configured: 4

any shift set up (even 0 or even 8) in  IndentGuide config causes decreasing of guides interval

**Comment by grosenberg** [comment]
Some fonts just don't report their size metrics correctly.

Liberation Mono is correct at 9 and 11, but not at 7, 8, or 10. 
Actually, most are correct at 9 and 11, but not at 7, 8, or 10. 
Source Code Pro seems never(?) correct.

Suspect there is some font size interpolation going on in the OS/JVM, but just do not know.

**Comment by grosenberg** [comment]
Fixed in release v 2.2.2

**Comment by molostoff** [comment]
Yes, tested OK, works fine!
