### ISSUE TITLE
Blank line guides are on the wrong line (Indent 2.2.2)

### ISSUE THREAD

**Issue by JanecekPetr** [grosenberg/IndentGuide#28]
Hello!

After updating to 2.2.2 the indent guides for blank lines are now like this with the default settings:
![image](https://user-images.githubusercontent.com/1746404/227936821-2441308c-5962-48b9-802f-f341727fd1e7.png)

You can see the guides for blank lines are one line below, and off to the left. I tried zooming, changing the font, restarting, nothing seems to make a difference. The log is clean. This happens both on the notebook's native display as well as as on an external monitor.

Is there any way I can help debug this problem?

IndentGuide 2.2.2
Eclipse 2023-03
MacOS Ventura on a MacBook Pro 14" with M1 Pro

**Comment by grosenberg** [comment]
Fix will be in the next release -- expect to publish within the next day or two, depending on testing.

**Comment by grosenberg** [comment]
2.2.4 has been published.

**Comment by JanecekPetr** [comment]
You, sir, are a gentleman, and a scholar! Thank you! <3
