### ISSUE TITLE
When a horizontal scroll bar appears, the alignment line will shift.

### ISSUE THREAD

**Issue by drc5521** [grosenberg/IndentGuide#29]
When a horizontal scroll bar appears, the alignment line will shift. When holding down the scroll bar and moving it left and right, the effect will be obvious.
![bug1](https://user-images.githubusercontent.com/55195642/230628510-c96e8692-cb5c-4615-9507-8ab01fd7d36a.png)

**Comment by grosenberg** [comment]
Fix will be available in the next release.

**Comment by grosenberg** [comment]
Released fix.
