### ISSUE TITLE
Unable to install IndentGuide

### ISSUE THREAD

**Issue by cesarmansur** [grosenberg/IndentGuide#3]
Hello. Since I last updated my DBeaver client, I am not able to install IndentGuide.
Could you please check this issue?

![image](https://user-images.githubusercontent.com/43681608/69683402-79ec7d00-1093-11ea-91a6-c21cf82adfd4.png)

**Comment by cesarmansur** [comment]
When using the URL "http://www.certiv.net/updates", IndentGuide is not listed below:

![image](https://user-images.githubusercontent.com/43681608/69683504-ce8ff800-1093-11ea-9dbf-60de390c1cef.png)

**Comment by grosenberg** [comment]
Fixed. Please retry the install.

**Comment by cesarmansur** [comment]
Thank you! :)
