### ISSUE TITLE
When using comment, the line will breaks.

### ISSUE THREAD

**Issue by drc5521** [grosenberg/IndentGuide#31]
When using comment, the line will breaks.
![line1](https://user-images.githubusercontent.com/55195642/232713456-ed76c607-ba94-4fd4-a046-b8230c5bdad9.png)
![line2](https://user-images.githubusercontent.com/55195642/232713573-118954f7-9a61-42ed-8d10-8887746b3a3a.png)

**Comment by grosenberg** [comment]
So, this is actually working as expected.  There is no discernible way to recognize the following blank lines as indented/requiring guides given the preceding comment line is less indented.  The guide properly returns for following lines with text.

Anything more would require semantic analysis.
