### ISSUE TITLE
Tab size not reflected

### ISSUE THREAD

**Issue by psprenger1** [grosenberg/IndentGuide#32]
My tabsize is 2 whitespaces, like in the google java styleguide.
IndentGuide is showing the lines on 4. Is it possible to change this to google style?

**Comment by grosenberg** [comment]
Indent guide picks up the tab width from  the preference set by `General` -> `Editors` -> `Displayed tab width`.

If that is in fact set to 2, please identify what editor/document type is showing a width of 4.
