### ISSUE TITLE
When the annotation symbol (//) is at the forefront, the line will break.

### ISSUE THREAD

**Issue by drc5521** [grosenberg/IndentGuide#33]
When the annotation symbol (//) is at the forefront, the line will break. (p1)
If there is no code on the next line of the comment, it will continue to extend.（p2）
![Snipaste_2023-06-06_10-06-50](https://github.com/grosenberg/IndentGuide/assets/55195642/531bef85-36b6-437c-a647-aa909067a6d1)
![Snipaste_2023-06-06_10-20-51](https://github.com/grosenberg/IndentGuide/assets/55195642/e5c0c90c-326c-4fbe-8334-69e22e92b70d)

**Comment by grosenberg** [comment]
Unclear from the pictures what is being described. 

What is perceived to be the problem?  What is  expected?

**Comment by drc5521** [comment]
> Unclear from the pictures what is being described.
> 
> What is perceived to be the problem? What is expected?



The dashed lines at the boxes in the figure should not be broken due to annotations.
![IMG_20230607_103703](https://github.com/grosenberg/IndentGuide/assets/55195642/d0a74bb2-0fe2-497d-8a8b-0fcdeb95ec98)
![IMG_20230607_103717](https://github.com/grosenberg/IndentGuide/assets/55195642/2a26d347-4de7-47d1-8e82-a43d65376d7a)

**Comment by grosenberg** [comment]
Fixed with version 2.4.0.
