### ISSUE TITLE
Can no longer download plugin into Eclipse

### ISSUE THREAD

**Issue by jbakeri4** [grosenberg/IndentGuide#34]
I wrote an e-mail to the domain that hosts the repository for this extension last month but received no reply. It is no longer possible to add this extension to installations of Eclipse:

**Problem Occurred:**
_No repository found at https://www.certiv.net/updates/net.certiv.indentguide.site._

Is this abandonware now?

**Comment by grosenberg** [comment]
The correct update site is ` https://www.certiv.net/updates/` 

The URL you listed __might__ have worked at some time, but any such sub-URL is internal and subject to change at any time.

**Comment by jbakeri4** [comment]
Thank you, I had tried that before but did not see IndentGuide listed, however, I do see it now. Cheers!
