### ISSUE TITLE
the update site is error : not found

### ISSUE THREAD

**Issue by zlay0701** [grosenberg/IndentGuide#35]
the update site
https://www.certiv.net/updates/net.certiv.indentguide.site
 is error : not found
what happend?
thanks

**Comment by grosenberg** [comment]
RTI. The update site is `https://www.certiv.net/updates/`

**Comment by jbakeri4** [comment]
Thank you, I had tried that before but did not see IndentGuide listed, however, I do see it now. Cheers!
