### ISSUE TITLE
Plugin doesn't work on Eclipse IDE for PHP Developers (includes Incubating components)

### ISSUE THREAD

**Issue by lknlnx** [grosenberg/IndentGuide#36]
Windows Version: 10.0.19045.4291

Eclipse:
Version: 2024-03 (4.31.0)
Build id: 20240307-1437

IndentGuide	2.4.0.20240221-0241	net.certiv.tools.indentguide.feature.feature.group	Certiv Analytis
JDK: 22.0.1.0

Tried with different file types, with different themes and different IndentGuide settings.
Eclipse reinstalled yesterday. Tried this plugin today for the first time.

**Comment by grosenberg** [comment]
Log file messages?
