### ISSUE TITLE
No slf4j provider error on using embedded maven after install this plug-in.

### ISSUE THREAD

**Issue by HJOW** [grosenberg/IndentGuide#38]
No slf4j provider error on using embedded maven after install this plug-in.

I cannot use embedded maven runtime, but external maven runtime is still work. Strange.

Why embedded runtime ignoring binding maven-slf4j-provider-3.8 6.jar ?

See following screen shots.

![indentguide_2.png](https://github.com/user-attachments/assets/b1e85c3b-f6b4-4c56-ae13-c6820874096b)

![indentguide_1.png](https://github.com/user-attachments/assets/7dc6c46d-bf73-42b5-ae60-b9f90efd94ba)

**Comment by grosenberg** [comment]
Indent Guide does not use SLF4J. The error message is irrelevant.
