### ISSUE TITLE
No preference page available

### ISSUE THREAD

**Issue by JanecekPetr** [grosenberg/IndentGuide#6]
I installed the newest IndentGuide on eclipse 2019.12 on macOS Catalina (10.15.2), and I cannot see the plugin preferences page:

<img width="193" alt="Screenshot 2020-01-06 at 11 39 39" src="https://user-images.githubusercontent.com/1746404/71813310-9360eb80-3079-11ea-834a-1cacd1e7cae9.png">

even though the plugin is listed among the installed plugins:

<img width="1023" alt="Screenshot 2020-01-06 at 11 43 08" src="https://user-images.githubusercontent.com/1746404/71813424-da4ee100-3079-11ea-88d8-ab27fda3c08b.png">

Is there anything I can do to help diagnosing the problem?

**Comment by grosenberg** [comment]
Please check the eclipse log for start-up errors and report any found. Might also want to try re-installing in any case.

**Comment by JanecekPetr** [comment]
No errors in the log at startup :-O. I've tried reinstalling the plugin, no luck. I'll try reinstalling eclipse next, I guess.

**Comment by JanecekPetr** [comment]
Yeah, reinstalling eclipse helped. No idea what went wrong, sorry for the false alarm!
