### ISSUE TITLE
IndentGuide does not show guides on multiple eclipse windows

### ISSUE THREAD

**Issue by molostoff** [grosenberg/IndentGuide#8]
When I open additional windows in Eclipse IDE (Window -> New Window menu item) indent guide displays only on the first (or last)  one, other windows do not display guides irrelevant to config settings, file type nor the perspective selected, e.g. works only in one window.

This seems to me a bit wrong, and would be kind if this exceptionally useful extension be working in multi-window/multi-display environments, thank you for your effort in supporting this marvelous thing.

The problem seems relevant up to latest Eclipse versions,  at least starting from Juno, and till now in the Version: 2021-03 M2 (4.19.0 M2) Build id: 20210204-1728

**Comment by grosenberg** [comment]
Unable to reproduce.  Works in all `Text` content type editors.

**Comment by molostoff** [comment]
Do not trust your open eyes, I still can not reproduce them working on all windows, even after you close it
![Screenshot_20210414_035533](https://user-images.githubusercontent.com/857920/114638984-7469f400-9cd5-11eb-8fa7-ae06f2a037d3.png)

If only you would like to take a picture with all these Text content type editors ...

**Comment by molostoff** [comment]
@grosenberg  Please, take a look here https://github.com/grosenberg/IndentGuide/blob/450d0a6ed4c9054abc57595adf9d5c70c3d38830/net.certiv.tools.indentguide/net.certiv.tools.indentguide.plugin/src/net/certiv/tools/indentguide/Starter.java#L49

**Comment by grosenberg** [comment]
What is the actual editor being used? Is the problem observed with other editors and, if so, which other editors.

At the bottom of the Indent Guide Preference page, the listed content types are **all** of the specific `text content type` file types that the workbench recognizes. Verify in Preferences -> General -> Content Types.

Note, the early startup code at line 49 is for capturing an editor that is open when the workbench starts up.  The `WindowWatcher` listener added to the workbench at line 60 captures later opened editors.

How are these new workbench windows being opened?  Indent Guide works correctly when using `Window` -> `New Window` when editing `java` files using the standard JDT editor.  

Finally, identify the Eclipse and JDK versions being used.

**Comment by molostoff** [comment]
On the image I have added as an example there are three PHP content type editors, any other text editor listed in the Indent Guide Preference page has exactly the same issue .

![Screenshot_20210414_105904](https://user-images.githubusercontent.com/857920/114677266-ced57580-9d12-11eb-9d81-40d6992e6afc.png)

A piece of preference page shows that PHP content type is enabled (all other types enabled as well, btw). 

Once new workbench window has created, it holds its configuration across restarts only when I exit workbench with File->Exit menu item (*not* Window Close - it destroys window and its config). Next workbench startup recovers its windows state and settings (including views, perspective configuration for each window, opened editors an so on)

So all these three windows on sample image were created by workbench at startup, without my additional intervention, and it seems to me the only last one has got Indent Guide hook


![Screenshot_20210414_110005](https://user-images.githubusercontent.com/857920/114679705-16f59780-9d15-11eb-8580-349573aaeffa.png)

![Screenshot_20210414_110106](https://user-images.githubusercontent.com/857920/114679738-1d840f00-9d15-11eb-98cb-56b887e54430.png)

**Comment by molostoff** [comment]
$ java -version
java version "14.0.2" 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

**Comment by grosenberg** [comment]
Requires testing.

[net.certiv.tools.indentguide.site-1.6.3-SNAPSHOT.zip](https://github.com/grosenberg/IndentGuide/files/6314941/net.certiv.tools.indentguide.site-1.6.3-SNAPSHOT.zip)

**Comment by molostoff** [comment]
Nope, the same result. Since the plugin version is the same, but not signed the same way as original plugin, I have removed original one from my install, and cleared workbench bundle pool cache.

![image](https://user-images.githubusercontent.com/857920/114855700-ea15b300-9dee-11eb-8446-43b1611c4db0.png)

IndentGuide still appears in the last window only, just after all windows are opened

**Comment by grosenberg** [comment]
Installed from the zip? The revision is 1.6.3 (1.6.3.20210415-0303).

What version is shown as installed.

**Comment by molostoff** [comment]
> Installed from the zip? The revision is 1.6.3 (1.6.3.20210415-0303).
> 
> What version is shown as installed.

Wow, Man! It works! Thank you very much! I love it :)

**Comment by molostoff** [comment]
Thankfully I close this issue!
