### ISSUE TITLE
Indent offset skewed when using autoscaling

### ISSUE THREAD

**Issue by Gelunox** [grosenberg/IndentGuide#9]
If I add `-Dswt.autoScale=150` to the eclipse.ini after `-vmargs` the position of every indent-line gets skewed 2 extra spaces going from 4 to 6. I'd assume this would increase to 4 extra spaces offset if I increase the autoscale factor to 200.

__Eclipse version__
Version: 2021-06 (4.20.0)
Build id: 20210612-2011

__OS__
Windows 10, 21H1

**Comment by grosenberg** [comment]
My understanding is that the swt.autoScale property is not meant to be used by end users. It’s just there as a fallback in case the JVM automatic detection somehow went terribly wrong.

I know of no way to test for the JVM setting from within the plugin.

A far better option is to directly set the text font size used by Eclipse.  

`Window->Preferences->General->Appearance->Colors and Fonts->Basic->Text Font`

**Comment by Gelunox** [comment]
I understand where  you're coming from, but I'm not using it to increase font size, I'm using it to increase icon size of toolbars and such (which is also what this feature is meant for).

Eclipse 4.6 what's new notes do go into how a user can tweak this setting to their preference https://www.eclipse.org/eclipse/news/4.6/platform.php#swt-autoscale-tweaks

something you could do from within the plugin is allow a negative offset, which may or may not help depending on how that stacks on multiple indents.
